matrix:
  include:
    - language: python
      python: 
        - "3.4"
      install:
        - pip install -r requires.txt

    - language: node_js
      node_js: 
        - "6"
      before_script:
        - cd server
